services:
  tokilane:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    volumes:
      - ./cmd/server/files:/app/files
      - ./data:/app/data
    environment:
      - PORT=1323
      - FILES_ROOT=/app/files
      - APP_LANG=en
      - DB_PATH=/app/data/app.db
      - DEBUG=false
    restart: unless-stopped
